FROM deb12-py-opencv:latest

RUN apt update
RUN apt install sqlite3

#install other requirements
COPY requirements.docker.py-3.10.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install pytest
